# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "dc555c25b932cb75ac9dbded41ff1fef"
name = "hide-shipping-rates"
handle = "hide-shipping-rates-6"
application_url = "https://addresses-oz-pleased-jungle.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "christian-functions-sandbox.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_delivery_customizations,write_products"

[auth]
redirect_urls = [
  "https://addresses-oz-pleased-jungle.trycloudflare.com/auth/callback",
  "https://addresses-oz-pleased-jungle.trycloudflare.com/auth/shopify/callback",
  "https://addresses-oz-pleased-jungle.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
